version: '3.5'
services:
  front_end:
    container_name: frontend
    build: .
    volumes:
      - ./:/SingularityTournament/tournament
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm start"